channels:
  - conda-forge
  - conda-incubator
dependencies:
  - affine==2.4.0
  - aiobotocore==2.15.2
  - aiohappyeyeballs==2.4.4
  - aiohttp==3.11.10
  - aioitertools==0.12.0
  - aiosignal==1.3.1
  - annotated-types==0.7.0
  - appnope==0.1.4
  - asttokens==3.0.0
  - attrs==24.2.0
  - backports.cached-property==1.0.2
  - boto3==1.35.36
  - botocore==1.35.36
  - branca==0.8.0
  - cachetools==5.5.0
  - certifi==2024.8.30
  - charset-normalizer==3.4.0
  - click==8.1.7
  - click-plugins==1.1.1
  - cligj==0.7.2
  - cloudpickle==3.1.0
  - comm==0.2.2
  - contourpy==1.3.1
  - cycler==0.12.1
  - dask==2024.12.0
  - debugpy==1.8.9
  - decorator==5.1.1
  - distributed==2024.12.0
  - executing==2.1.0
  - fiona==1.10.1
  - folium==0.19.0
  - fonttools==4.55.3
  - frozenlist==1.5.0
  - fsspec==2024.10.0
  - geopandas==1.0.1
  - idna==3.10
  - ipykernel==6.29.5
  - ipython==8.30.0
  - jedi==0.19.2
  - Jinja2==3.1.4
  - jmespath==1.0.1
  - joblib==1.4.2
  - jsonschema==4.23.0
  - jsonschema-specifications==2024.10.1
  - jupyter_client==8.6.3
  - jupyter_core==5.7.2
  - kiwisolver==1.4.7
  - locket==1.0.0
  - Mako==1.3.8
  - mapclassify==2.8.1
  - Markdown==3.7
  - MarkupSafe==3.0.2
  - matplotlib==3.9.3
  - matplotlib-inline==0.1.7
  - max-ard==1.7.4
  - maxar-ard-grid==1.2.2
  - msgpack==1.1.0
  - multidict==6.1.0
  - nest-asyncio==1.6.0
  - networkx==3.4.2
  - numpy==2.2.0
  - oauthlib==3.2.2
  - odc-geo==0.4.8
  - odc-stac==0.3.10
  - packaging==24.2
  - pandas==2.2.3
  - parso==0.8.4
  - partd==1.4.2
  - pdoc3==0.10.0
  - pexpect==4.9.0
  - pillow==11.0.0
  - platformdirs==4.3.6
  - prompt_toolkit==3.0.48
  - propcache==0.2.1
  - psutil==6.1.0
  - ptyprocess==0.7.0
  - pure_eval==0.2.3
  - pydantic==2.10.3
  - pydantic_core==2.27.1
  - Pygments==2.18.0
  - pyogrio==0.10.0
  - pyparsing==3.2.0
  - pyproj==3.7.0
  - pystac==1.11.0
  - pystac-client==0.8.5
  - python-dateutil==2.9.0.post0
  - pytz==2024.2
  - PyYAML==6.0.2
  - pyzmq==26.2.0
  - rasterio==1.4.3
  - referencing==0.35.1
  - requests==2.32.3
  - requests-futures==1.0.2
  - requests-oauthlib==1.3.1
  - rpds-py==0.22.3
  - s3fs==0.4.2
  - s3transfer==0.10.4
  - scikit-learn==1.6.0
  - scipy==1.14.1
  - shapely==2.0.6
  - six==1.17.0
  - sortedcontainers==2.4.0
  - stack-data==0.6.3
  - tblib==3.0.0
  - threadpoolctl==3.5.0
  - toolz==1.0.0
  - tornado==6.4.2
  - traitlets==5.14.3
  - typing_extensions==4.12.2
  - tzdata==2024.2
  - urllib3==2.2.3
  - wcwidth==0.2.13
  - wrapt==1.17.0
  - xarray==2024.11.0
  - xyzservices==2024.9.0
  - yarl==1.18.3
  - zict==3.0.0
